server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Для React Router: всегда отдаём index.html
    location / {
        try_files $uri /index.html;
    }

    # Чтобы не было ошибок в логах
    location = /favicon.ico { log_not_found off }
    location = /apple-touch-icon.png { log_not_found off }
    location = /apple-touch-icon-precomposed.png { log_not_found off }
}
